set -g mouse on
set -sg escape-time 1

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
bind-key , command-prompt -I "#W" "rename-window '%%'; setw automatic-rename off"

##### =========================
##### TERMINAL FIXES
##### =========================
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

##### =========================
##### GRUVBOX THEME
##### =========================
# Matches alacritty + nvim gruvbox dark (bg0 #282828, fg #ebdbb2)

set -g status-position top

set -g mode-style "fg=#282828,bg=#fabd2f"

set -g message-style "fg=#282828,bg=#fabd2f"
set -g message-command-style "fg=#282828,bg=#fabd2f"

set -g pane-border-style "fg=#504945"
set -g pane-active-border-style "fg=#fabd2f"

set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#ebdbb2,bg=#282828"

set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#282828,bg=#d3869b,bold] #S #[fg=#d3869b,bg=#282828,nobold] "
set -g status-right "#[fg=#282828,bg=#d3869b,bold] #(~/.dotfiles/tmux/status-datetime.sh) "

setw -g window-status-activity-style "fg=#ebdbb2,bg=#282828"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#665c54,bg=#282828"
setw -g window-status-format "#[fg=#665c54,bg=#282828] #I #W "
setw -g window-status-current-format "#[fg=#282828,bg=#fabd2f,bold] #I #W "

set -g clock-mode-colour "#fabd2f"
set -g copy-mode-match-style "fg=#282828,bg=#fabd2f"
set -g copy-mode-current-match-style "fg=#282828,bg=#b8bb26"

##### =========================
##### INDEXING (1-based)
##### =========================
set -g base-index 1
set -g pane-base-index 1

##### =========================
##### AUTO WINDOW NAMING
##### =========================
setw -g automatic-rename on
##setw -g automatic-rename-format '#{pane_current_command}'
set -g automatic-rename-format ' #{pane_current_command} '

##### =========================
##### SPLITS AND WINDOWS
##### =========================
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind c new-window -c "#{pane_current_path}"

##### =========================
##### VIM-STYLE NAVIGATION
##### =========================
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

##### =========================
##### PERSISTENT RENAMING
##### =========================
bind-key , command-prompt -I "#W" "rename-window '%%'; setw automatic-rename off"

# Vim mode cursor change
set -as terminal-features ',xterm-256color:extkeys'
set -ga terminal-overrides ',xterm-256color:Ss=\E[%p1%d q:Se=\E[2 q'

##### =========================
##### PLUGINS
##### =========================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jaclu/tmux-menus'

# Initialize TMUX plugin manager (keep this at bottom)
run '~/.tmux/plugins/tpm/tpm'

